name: ClimaxKits
main: net.climaxmc.KitPvp.Main
version: 1.2
authors: [computerwizjared, jonhan2000]
depend: [Vault]
commands:
  repair:
    description: Repairs your inventory!
    permission: ClimaxKits.Repair