Database:
  Host: localhost
  Port: 3306
  Database: ClimaxPvp
  Username: root
  Password: password
SpawnAutoBroadcast:
  Time: 5
  Messages:
    - This is an auto broadcast message!
    - This is another auto broadcast message!
ChatAutoBroadcast:
  Time: 5
  Messages:
    - This is an auto broadcast message!
    - This is another auto broadcast message!
HighestPlayerCount: 0