name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
authors: [computerwizjared, jonhan2000]
depend: [Vault]
commands:
  repair:
    description: Repairs your inventory
    permission: ${project.artifactId}.Repair
  spawn:
    description: Teleports you to spawn
  1v1:
    description: Joins the 1v1 arena
  trails:
    descriptions: Displays the trails inventory
  spectate:
    aliases: spec
    description: Spectate the pvp arena
    permission: ${project.artifactId}.Spectate