name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
authors: [computerwizjared, Jonhan]
commands:
  repair:
    description: Repairs your inventory for $2
  spawn:
    description: Teleports you to spawn
  balance:
    aliases: bal
    description: Gets your balance
  economy:
    aliases: eco
    description: Economy management
  pay:
    description: Pay a player
  trails:
    descriptions: Displays the trails inventory
  spectate:
    aliases: spec
    description: Spectate the pvp arena
  statistics:
    aliases: stats
    description: Displays a player's stats
  nickname:
    aliases: nick
    description: Create a nickname
  admin:
    description: Enables admin access to all kits
  warp:
    description: Warp to a different location
  suicide:
    description: Commit suicide
  help:
    description: Help
  rules:
    description: Rules
  inventory:
    description: Open player inventory
    aliases: inv
  message:
    description: Message a player
    aliases: [msg, m, tell, w, t]
  reply:
    description: Reply to a message
    aliases: r
  ping:
    description: Get your ping or the ping of another player
  soup:
    description: Opens an inventory of soup for $10
  report:
    description: Report a player for hacking
  list:
    description: List online players
  vanish:
    description: Vanish to watch players
    aliases: v
  check:
    description: Check a player
  realname:
    description: Figure out what a player's real name is
  baltop:
    description: View the top balances
  youtube:
    description: Enables YouTube/Twitch access to all kits
    aliases: twitch
  clearchat:
    description: Clears the chat using spaces
    aliases: [cchat, cc]
  rank:
    description: Sets the rank of a player
  pei:
    description: Receive a Pei!
  ban:
    description: Ban a player
  tempban:
    description: Temporarily ban a player
  unban:
    description: Unban a player
  mute:
    description: Mute a player
  tempmute:
    description: Temporarily mute a player
  unmute:
    description: Unmute a player
  kick:
    description: Kick a player
  donate:
    description: View donation link
    aliases: [buy, shop]
  ip:
    description: Get the IP of a player