name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
authors: [computerwizjared, Jonhan_]
commands:
  repair:
    description: Repairs your inventory
  spawn:
    description: Teleports you to spawn
  balance:
    aliases: bal
    description: Gets your balance
  economy:
    aliases: eco
    description: Economy management
  pay:
    description: Pay a player
  trails:
    descriptions: Displays the trails inventory
  spectate:
    aliases: spec
    description: Spectate the pvp arena
  statistics:
    aliases: stats
    description: Displays a player's stats
  nickname:
    aliases: nick
    description: Create a nickname
  admin:
    description: Enables admin access to all kits
  warp:
    description: Warp to a different location
  suicide:
    description: Commit suicide
  help:
    description: Help
  rules:
    description: Rules
  inventory:
    description: Open player inventory
    aliases: inv
  message:
    description: Message a player
    aliases: [msg, m, tell]
  reply:
    description: Reply to a message
    aliases: r