name: ClimaxPvp
main: net.climaxmc.ClimaxPvp
version: 1.2
authors: [computerwizjared, jonhan2000]
depend: [Vault]
commands:
  repair:
    description: Repairs your inventory
    permission: ClimaxPvp.Repair
  spawn:
    description: Teleports you to spawn
  1v1:
    description: Joins the 1v1 arena
  particles:
    descriptions: Displays the particles inventory