name: ClimaxPvp
main: net.climaxmc.ClimaxPvp
version: 3.0-SNAPSHOT
authors: [computerwizjared, Jonhan, GamerBah]
softdepend: [ProtocolLib, AntiNub]
commands:
  repair:
    description: Repairs your inventory for $2
  spawn:
    description: Teleports you to spawn
  balance:
    aliases: bal
    description: Gets your balance
  economy:
    aliases: eco
    description: Economy management
  pay:
    description: Pay a player
  trails:
    descriptions: Displays the trails inventory
  spectate:
    aliases: spec
    description: Spectate the pvp arena
  statistics:
    aliases: stats
    description: Displays a player's stats
  nickname:
    aliases: nick
    description: Create a nickname
  admin:
    description: Enables admin access to all kits
  warp:
    description: Warp to a different location
  suicide:
    description: Commit suicide
  help:
    description: Help
  rules:
    description: Rules
  inventory:
    description: Open player inventory
    aliases: inv
  message:
    description: Message a player
    aliases: [msg, m, tell, w, t]
  reply:
    description: Reply to a message
    aliases: r
  ping:
    description: Get your ping or the ping of another player
  soup:
    description: Opens an inventory of soup for $10
  report:
    description: Report a player for hacking
  list:
    description: List online players
  vanish:
    description: Vanish to watch players
    aliases: v
  check:
    description: Check a player
  realname:
    description: Figure out what a player's real name is
  baltop:
    description: View the top balances
  youtube:
    description: Enables YouTube/Twitch access to all kits
    aliases: twitch
  clearchat:
    description: Clears the chat using spaces
    aliases: [cchat, cc]
  rank:
    description: Sets the rank of a player
  pei:
    description: Receive a Pei!
  donate:
    description: View donation link
    aliases: [buy, shop]
  cmdspy:
    description: Toggles command spy on and off
    aliases: [spy, commandspy, cspy]
  lockchat:
    description: Locks or unlocks the chat
    aliases: [lc, lchat]
  team:
    description: Team up with another player
    aliases: ally
  staff:
    description: In-game Staff Chat
    aliases: [s, staffchat]
  getip:
    description: Get a player's IP address
    aliases: ip
  alert:
    description: Sends an alert to the server
    aliases: a
  freeze:
    description: Freezes all players
    aliases: ss
  staffreq:
    description: Sends a message to offline Staff Members
    aliases: [staffhelp, shelp, sreq]
  afk:
    description: Makes a player AFK (away from keyboard)
  options:
    description: Opens the options menu for a player
  staffalert:
    description: Alerts all staff online with a msg
    aliases: sa
  duel:
    description: Duel a player
  unlocktrail:
    description: Unlock any trail for any player
  usetoken:
    description: Whitelist a player of your choice
  settokens:
    description: Set the tokens of a player
  donatebroadcast:
    description: Broadcast a donation
  cosmetics:
    description: Open cosmetics menu
    aliases: c
  tournament:
    description: Tournament control command
    aliases: tourney
  unlockdeatheffect:
    description: Unlock any death effect for any player
  unbancombat:
    description: Unbans a player that was banned because of combat log protection
    aliases: unbanc
  top:
    description: View leaderboards
  rotatemaps:
    description: Manually rotates the maps
  statshologram:
    description: Hologram creation command
  hub:
    description: Sends player to hub
  resetstats:
    description: Resets stats for a player
  event:
    description: Event management command
  #tag:
  #  description: Main control command for tag games