name: ClimaxPvp
main: net.climaxmc.ClimaxPvp
version: 1.2
authors: [computerwizjared, jonhan2000]
depend: [Vault]
commands:
  repair:
    description: Repairs your inventory
    permission: ClimaxKits.Repair
  spawn:
    description: Teleports you to spawn
  1v1:
    description: Joins the 1v1 arena
  setlobby:
  setarena1spawn1:
  setarena1spawn2:
  setarena2spawn1:
  setarena2spawn2:
  setarena3spawn1:
  setarena3spawn2: