name: ClimaxPvp
main: net.climaxmc.ClimaxPvp
version: 1.2
authors: [computerwizjared, jonhan2000]
depend: [Vault]
commands:
  repair:
    description: Repairs your inventory
    permission: ClimaxKits.Repair
  spawn:
    description: Teleports you to spawn
  1v1:
    description: Joins the 1v1 arena
  pvp:
    description: Applies Kit Pvp
  heavy:
    description: Applies Kit Heavy
  archer:
    description: Applies Kit Archer
  soldier:
    description: Applies Kit Soldier
  irongolem:
    description: Applies Kit Iron Golem
  fisherman:
    description: Applies Kit Fisherman
  ninja:
    description: Applies Kit Ninja
