name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
authors: [computerwizjared, Jonhan_]
commands:
  rank:
    description: Rank management
  repair:
    description: Repairs your inventory
    permission: ${project.artifactId}.Repair
  spawn:
    description: Teleports you to spawn
  1v1:
    description: Joins the 1v1 arena
  balance:
    aliases: bal
    description: Gets your balance
  economy:
    aliases: eco
    description: Economy management
  pay:
    description: Pay a player
  trails:
    descriptions: Displays the trails inventory
  spectate:
    aliases: spec
    description: Spectate the pvp arena
    permission: ${project.artifactId}.Spectate
  statistics:
    aliases: stats
    description: Displays a player's stats